---
output: html_document
---
# Info498F Class Survey

```{r, echo=FALSE, message=FALSE}
library(plotly, warn.conflicts = FALSE)
library(dplyr)

# Read in functions from another file:
source('scripts/summary_info.R')
source('scripts/chart2.R')
source('scripts/Chart 1.R')

# Read in data
data <- read.csv("https://raw.githubusercontent.com/INFO-498F/a7-survey-data/master/intro_survey_data.csv")

# pass data to get basic list of information about the data
summary <- summary_info(data)
```
This is a brief summary report of the data collected by the survery current info498 took.
In total, `r summary$participants` number of students participated this survey. 
Students were asked to answer `r summary$num_questions` basic questions. 
The survey asks students general questions such as `r summary$questions[1:3]`.

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# pass data to render chart 1 
build_plot(data)
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
# pass data to render chart 2
visited_countries(data)
```

